version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo "Installing dependencies"
      - mvn install
  build:
    commands:
      - echo "Building the project"
      - mvn clean package
  post_build:
    commands:
      - echo "Zipping the application and uploading to S3"
      - zip -r my-app.zip target/*.jar
      - aws s3 cp my-app.zip s3://your-s3-bucket-name/
